import type { Metadata } from "next";
import "./globals.css";
import Wrapper from "@/components/Wrapper";
import ReduxProvider from "@/components/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-primary`}>
        <ReduxProvider>
          <Wrapper>{children}</Wrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
